/*#priority 3000
#loader contenttweaker
import scripts.contenttweaker.functions.createRegisterBlockOre;
import scripts.contenttweaker.functions.createRegisterDirtOre;

createRegisterBlockOre("ore_adamantium", 4);
createRegisterBlockOre("ore_chrome", 4);
createRegisterBlockOre("ore_coal", 1);
createRegisterBlockOre("ore_diamond", 2);
createRegisterBlockOre("ore_emerald", 2);
createRegisterBlockOre("ore_gold", 1);
createRegisterBlockOre("ore_iron", 1);
createRegisterBlockOre("ore_lapis", 2);
createRegisterBlockOre("ore_manganese", 2);
createRegisterBlockOre("ore_platinum", 3);
createRegisterBlockOre("ore_redstone", 2);
createRegisterBlockOre("ore_tin", 1);
createRegisterBlockOre("ore_tungsten", 4);
createRegisterBlockOre("ore_iridium", 4);

createRegisterDirtOre("deposit_adamantium", 4);
createRegisterDirtOre("deposit_aluminum", 1);
createRegisterDirtOre("deposit_chrome", 4);
createRegisterDirtOre("deposit_coal", 1);
createRegisterDirtOre("deposit_copper", 1);
createRegisterDirtOre("deposit_diamond", 2);
createRegisterDirtOre("deposit_emerald", 2);
createRegisterDirtOre("deposit_gold", 1);
createRegisterDirtOre("deposit_iron", 1);
createRegisterDirtOre("deposit_lapis", 2);
createRegisterDirtOre("deposit_lead", 1);
createRegisterDirtOre("deposit_manganese", 2);
createRegisterDirtOre("deposit_nickel", 2);
createRegisterDirtOre("deposit_platinum", 3);
createRegisterDirtOre("deposit_redstone", 2);
createRegisterDirtOre("deposit_silver", 2);
createRegisterDirtOre("deposit_tin", 1);
createRegisterDirtOre("deposit_tungsten", 4);
createRegisterDirtOre("deposit_uranium", 4);
createRegisterDirtOre("deposit_iridium", 4);
*/